channels:
  - conda-forge
dependencies:
  - python==3.8.15
  - click==8.0.1
  - graphviz==7.1.0
  - gitpython==3.1.26
  - ipykernel==6.2.0
  - ipywidgets==7.6.3
  - jupyterlab==3.2.8
  - jupyterlab-plotly-extension==1.0.0
  - jsonschema==3.2.0
  - matplotlib==3.4.2
  - numba==0.55.2
  - numpy==1.22.4
  - openpyxl==3.1.1
  - pandas==1.5.3
  - pip==23.0.1
  - plotly==5.13.1
  - pyodbc==4.0.35
  - pytest==6.2.2
  - requests==2.25.1
  - scikit-learn==1.2.2
  - scipy==1.9.3
  - seaborn==0.11.1
  - tqdm==4.64.1
  - typing_extensions==4.5.0
  - xgboost==1.7.1
  - pip:
    - azureml-core==1.49.0
    - azureml-mlflow==1.49.0
    - azureml-pipeline==1.49.0
    - azureml-datadrift==1.49.0
    - azureml-defaults==1.49.0
    - mlflow-skinny==2.3.0
    - typesentry==0.2.7
